//! Mask maths for full-resolution export. This is a line-for-line port of
//! `src/canvas/maskOps.ts` (used for the interactive preview); `tests/fixtures/mask_parity.json`
//! (generated by the TypeScript tests) keeps the two implementations in agreement.
//!
//! Units: `feather` and `edge_shift` are SOURCE pixels; `scale` converts them to buffer pixels
//! (1.0 at full resolution).

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", default)]
pub struct RefineParams {
    /// 0..=100. Higher keeps less.
    pub threshold: f64,
    /// 0..=20 source px of Gaussian softening.
    pub feather: f64,
    /// -20..=20 source px. Positive grows the subject.
    pub edge_shift: f64,
}

impl Default for RefineParams {
    fn default() -> Self {
        Self {
            threshold: 50.0,
            feather: 2.0,
            edge_shift: 0.0,
        }
    }
}

impl RefineParams {
    /// Clamp into the ranges the editor allows (saved files are untrusted input).
    pub fn clamped(self) -> Self {
        let f = |v: f64, lo: f64, hi: f64| {
            if v.is_finite() {
                v.clamp(lo, hi)
            } else {
                lo.max(0.0)
            }
        };
        Self {
            threshold: f(self.threshold, 0.0, 100.0),
            feather: f(self.feather, 0.0, 20.0),
            edge_shift: if self.edge_shift.is_finite() {
                self.edge_shift.clamp(-20.0, 20.0)
            } else {
                0.0
            },
        }
    }
}

const SOFT_WIDTH: f64 = 32.0;

/// JS `Math.round` (ties toward +infinity), so results match the TypeScript implementation.
fn js_round(v: f64) -> f64 {
    (v + 0.5).floor()
}

pub fn soft_threshold_lut(threshold: f64) -> [u8; 256] {
    let t = threshold.clamp(0.0, 100.0) / 100.0;
    let centre = SOFT_WIDTH + t * (255.0 - 2.0 * SOFT_WIDTH);
    let mut lut = [0u8; 256];
    for (v, slot) in lut.iter_mut().enumerate() {
        let x = (v as f64 - (centre - SOFT_WIDTH)) / (2.0 * SOFT_WIDTH);
        *slot = js_round(255.0 * x.clamp(0.0, 1.0)) as u8;
    }
    lut
}

/// Sliding-window min/max along one row (monotonic deque, O(n)).
fn slide_row(src: &[u8], dst: &mut [u8], radius: usize, is_max: bool, deque: &mut [i32]) {
    let n = src.len();
    let (mut head, mut tail, mut next) = (0usize, 0usize, 0usize);
    #[allow(clippy::needless_range_loop)]
    for i in 0..n {
        let hi = (n - 1).min(i + radius);
        while next <= hi {
            let v = src[next];
            while tail > head {
                let last = src[deque[tail - 1] as usize];
                if (is_max && last <= v) || (!is_max && last >= v) {
                    tail -= 1;
                } else {
                    break;
                }
            }
            deque[tail] = next as i32;
            tail += 1;
            next += 1;
        }
        while (deque[head] as i64) < i as i64 - radius as i64 {
            head += 1;
        }
        dst[i] = src[deque[head] as usize];
    }
}

fn transpose(src: &[u8], dst: &mut [u8], w: usize, h: usize) {
    for y in 0..h {
        for x in 0..w {
            dst[x * h + y] = src[y * w + x];
        }
    }
}

/// Square-element dilate (max) or erode (min) with the given pixel radius.
pub fn morph(src: &[u8], w: usize, h: usize, radius: f64, dilate: bool) -> Vec<u8> {
    let r = js_round(radius) as usize;
    if r == 0 {
        return src.to_vec();
    }
    let mut a = vec![0u8; w * h];
    let mut b = vec![0u8; w * h];
    let mut deque = vec![0i32; w.max(h) + 1];
    for y in 0..h {
        slide_row(
            &src[y * w..(y + 1) * w],
            &mut a[y * w..(y + 1) * w],
            r,
            dilate,
            &mut deque,
        );
    }
    transpose(&a, &mut b, w, h);
    for x in 0..w {
        slide_row(
            &b[x * h..(x + 1) * h],
            &mut a[x * h..(x + 1) * h],
            r,
            dilate,
            &mut deque,
        );
    }
    transpose(&a, &mut b, h, w);
    b
}

fn box_sizes(sigma: f64, n: usize) -> Vec<usize> {
    let w_ideal = ((12.0 * sigma * sigma) / n as f64 + 1.0).sqrt();
    let mut wl = w_ideal.floor() as i64;
    if wl % 2 == 0 {
        wl -= 1;
    }
    let wu = wl + 2;
    let nf = n as f64;
    let wlf = wl as f64;
    let m = js_round(
        (12.0 * sigma * sigma - nf * wlf * wlf - 4.0 * nf * wlf - 3.0 * nf) / (-4.0 * wlf - 4.0),
    );
    (0..n)
        .map(|i| if (i as f64) < m { wl } else { wu } as usize)
        .collect()
}

fn round_table(div: usize) -> Vec<u8> {
    let half = div >> 1;
    (0..=255 * div).map(|v| ((v + half) / div) as u8).collect()
}

fn box_blur_h(src: &[u8], dst: &mut [u8], w: usize, h: usize, r: usize) {
    let tbl = round_table(2 * r + 1);
    for y in 0..h {
        let row = &src[y * w..(y + 1) * w];
        let out = &mut dst[y * w..(y + 1) * w];
        let at = |i: i64| row[i.clamp(0, w as i64 - 1) as usize] as i64;
        let mut acc = (r as i64 + 1) * at(0);
        for j in 1..=r as i64 {
            acc += at(j);
        }
        for x in 0..w as i64 {
            out[x as usize] = tbl[acc as usize];
            acc += at(x + r as i64 + 1) - at(x - r as i64);
        }
    }
}

fn box_blur_v(src: &[u8], dst: &mut [u8], w: usize, h: usize, r: usize) {
    let tbl = round_table(2 * r + 1);
    let mut acc = vec![0i64; w];
    for x in 0..w {
        acc[x] = (r as i64 + 1) * src[x] as i64;
    }
    for j in 1..=r {
        let o = j.min(h - 1) * w;
        for x in 0..w {
            acc[x] += src[o + x] as i64;
        }
    }
    for y in 0..h as i64 {
        let o = y as usize * w;
        let add_o = (y + r as i64 + 1).min(h as i64 - 1) as usize * w;
        let sub_o = (y - r as i64).max(0) as usize * w;
        for x in 0..w {
            let a = acc[x];
            dst[o + x] = tbl[a as usize];
            acc[x] = a + src[add_o + x] as i64 - src[sub_o + x] as i64;
        }
    }
}

/// Gaussian blur approximated by three box blurs (same box sizes as the TypeScript version).
pub fn gaussian_blur(src: &[u8], w: usize, h: usize, sigma: f64) -> Vec<u8> {
    if sigma < 0.5 || w == 0 || h == 0 {
        return src.to_vec();
    }
    let mut a = src.to_vec();
    let mut b = vec![0u8; w * h];
    for size in box_sizes(sigma, 3) {
        let r = (((size as f64 - 1.0) / 2.0).max(1.0)) as usize;
        box_blur_h(&a, &mut b, w, h, r);
        box_blur_v(&b, &mut a, w, h, r);
    }
    a
}

/// Soft threshold, then edge shift, then feather. Never mutates `base`.
pub fn compute_refined(
    base: &[u8],
    w: usize,
    h: usize,
    params: RefineParams,
    scale: f64,
) -> Vec<u8> {
    let p = params.clamped();
    let lut = soft_threshold_lut(p.threshold);
    let mut m: Vec<u8> = base.iter().map(|&v| lut[v as usize]).collect();

    let shift = p.edge_shift.abs() * scale;
    if js_round(shift) >= 1.0 {
        m = morph(&m, w, h, shift, p.edge_shift > 0.0);
    }
    let sigma = p.feather * scale;
    if sigma >= 0.5 {
        m = gaussian_blur(&m, w, h, sigma);
    }
    m
}

/// `final = clamp(refined + delta)`, where `delta` holds keep (+) and erase (-) edits.
pub fn compose_final(refined: &[u8], delta: &[i16], out: &mut [u8]) {
    for ((o, &r), &d) in out.iter_mut().zip(refined).zip(delta) {
        *o = (r as i32 + d as i32).clamp(0, 255) as u8;
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn grid(w: usize, h: usize, f: impl Fn(usize, usize) -> u8) -> Vec<u8> {
        (0..w * h).map(|i| f(i % w, i / w)).collect()
    }

    #[test]
    fn lut_keeps_extremes_and_is_monotonic() {
        for t in [0.0, 25.0, 50.0, 75.0, 100.0] {
            let l = soft_threshold_lut(t);
            assert_eq!((l[0], l[255]), (0, 255));
            assert!(l.windows(2).all(|p| p[0] <= p[1]));
        }
        assert!(soft_threshold_lut(80.0)[128] < soft_threshold_lut(20.0)[128]);
    }

    #[test]
    fn morph_grows_and_shrinks_a_square_exactly() {
        let sq = grid(21, 21, |x, y| {
            if (8..=12).contains(&x) && (8..=12).contains(&y) {
                255
            } else {
                0
            }
        });
        let count = |m: &[u8]| m.iter().filter(|&&v| v == 255).count();
        assert_eq!(count(&morph(&sq, 21, 21, 2.0, true)), 81);
        assert_eq!(count(&morph(&sq, 21, 21, 2.0, false)), 1);
        assert_eq!(morph(&sq, 21, 21, 0.0, true), sq);
    }

    #[test]
    fn blur_preserves_flat_fields_and_spreads_points() {
        assert!(gaussian_blur(&vec![200; 900], 30, 30, 3.0)
            .iter()
            .all(|&v| v == 200));
        let spot = grid(31, 31, |x, y| if x == 15 && y == 15 { 255 } else { 0 });
        let b = gaussian_blur(&spot, 31, 31, 2.0);
        let sum: i64 = b.iter().map(|&v| v as i64).sum();
        assert!((sum - 255).abs() < 40);
        assert!(b[15 * 31 + 15] < 255);
        assert_eq!(gaussian_blur(&spot, 31, 31, 0.2), spot);
    }

    #[test]
    fn refine_does_not_touch_the_base_and_scales_units() {
        let base = grid(40, 40, |x, y| {
            if (10..30).contains(&x) && (10..30).contains(&y) {
                255
            } else {
                0
            }
        });
        let copy = base.clone();
        let p = |edge| RefineParams {
            threshold: 50.0,
            feather: 0.0,
            edge_shift: edge,
        };
        let half = compute_refined(&base, 40, 40, p(4.0), 0.5);
        let direct = compute_refined(&base, 40, 40, p(2.0), 1.0);
        assert_eq!(half, direct);
        assert_eq!(base, copy);
    }

    #[test]
    fn hostile_params_are_clamped() {
        let p = RefineParams {
            threshold: f64::NAN,
            feather: 1e9,
            edge_shift: -1e9,
        }
        .clamped();
        assert_eq!((p.feather, p.edge_shift), (20.0, -20.0));
        assert!(p.threshold.is_finite());
    }

    #[test]
    fn compose_clamps() {
        let mut out = [0u8; 4];
        compose_final(&[0, 100, 250, 255], &[-50, 50, 50, -300], &mut out);
        assert_eq!(out, [0, 150, 255, 0]);
    }
}
